// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ogrodnik_lab2;

#nullable disable

namespace Ogrodnik_lab2.Migrations
{
    [DbContext(typeof(DancersDBContext))]
    partial class DancersDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Ogrodnik_lab2.DancerDB", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("danceClubName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dancePartnerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("danceclass")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Dancerss");

                    b.HasData(
                        new
                        {
                            id = 20,
                            danceClubName = "Wygibasy",
                            dancePartnerName = "Dupson",
                            danceclass = "A",
                            name = "Dupa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
